ruby-buildpack/ruby_buildpack-cflinuxfs4-v1.10.29.zip:
  size: 5159197
  object_id: 259875a3-e5c4-44c6-4cf8-8acf05a4ae41
  sha: sha256:1250e4b13662861354e92fcc8649416e837e5b905bebe74351ed10e252676234
